org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

POSTER_PILOT_KEYSTORE_FILE=C:\\Users\\srama\\AndroidKeys\\posterpilot-upload-key.jks
POSTER_PILOT_KEYSTORE_PASSWORD=Xenx@684202
POSTER_PILOT_KEY_ALIAS=posterpilot
POSTER_PILOT_KEY_PASSWORD=Xenx@684202